In [13]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
carData = pd.read_csv('car_data.csv')
whole = carData.describe()
x = carData.drop(columns=['price'])
y = carData['']

,Unnamed: 0.1,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,city-L/100km,horsepower-binned,diesel,gas
0,0,0,3,122,alfa-romero,std,two,convertible,rwd,front,...,2.68,9.0,111.0,5000.0,21,27,11.190476,Medium,0,1
1,1,1,3,122,alfa-romero,std,two,convertible,rwd,front,...,2.68,9.0,111.0,5000.0,21,27,11.190476,Medium,0,1
2,2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,...,3.47,9.0,154.0,5000.0,19,26,12.368421,Medium,0,1
3,3,3,2,164,audi,std,four,sedan,fwd,front,...,3.40,10.0,102.0,5500.0,24,30,9.791667,Medium,0,1
4,4,4,2,164,audi,std,four,sedan,4wd,front,...,3.40,8.0,115.0,5500.0,18,22,13.055556,Medium,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196,196,-1,95,volvo,std,four,sedan,rwd,front,...,3.15,9.5,114.0,5400.0,23,28,10.217391,Medium,0,1
197,197,197,-1,95,volvo,turbo,four,sedan,rwd,front,...,3.15,8.7,160.0,5300.0,19,25,12.368421,High,0,1
198,198,198,-1,95,volvo,std,four,sedan,rwd,front,...,2.87,8.8,134.0,5500.0,18,23,13.055556,Medium,0,1
199,199,199,-1,95,volvo,turbo,four,sedan,rwd,front,...,3.40,23.0,106.0,4800.0,26,27,9.038462,Medium,1,0
200,200,200,-1,95,volvo,turbo,four,sedan,rwd,front,...,3.15,9.5,114.0,5400.0,19,25,12.368421,Medium,0,1